export const uiStrings = {
  slideLabel: "Folie",
  of: "von",
  prev: "Zurück",
  next: "Weiter",
  progress: "Fortschritt",
  copyLink: "Link zu dieser Folie kopieren",
  copied: "Kopiert",
  presenterMode: "Presenter-Modus",
  presenterHint:
    "Presenter: Pfeiltasten oder Leertaste. Home/Ende für Anfang/Ende. «Link kopieren» erzeugt einen Link fürs Publikum (ohne /present).",
  studentHint:
    "Du siehst dieselbe Folie wie der Vortrag, sobald jemand live präsentiert. Selbst blättern? Tippe danach LIVE, um wieder mitzugehen.",
  presenterViewBadge: "Presenter-Ansicht",
  presenterKeyLabel: "Presenter-Code",
  presenterKeyPlaceholder:
    "Vollständigen Wert von PRESENTER_SECRET einfügen (.env.local oder Vercel)",
  presenterKeyStored: "Code wird für diese Sitzung gespeichert (nur in diesem Browser).",
  followPresenter: "Folien dem Vortragenden folgen",
  followHint:
    "Optional: mit dem Publikum mitschauen (Realtime). Für das Publikum ist Live-Follow standardmässig aktiv.",
  synced: "LIVE",
  liveResumeCta: "LIVE",
  liveResumeHint: "Zurück zur Live-Folie",
  liveFollowingHint: "Synchron mit dem Vortrag",
  openWebsite: "Webseite öffnen",
  reactionsTitle: "Zeig kurz dein Feedback",
  reactionsHint:
    "Je mehr kurz hintereinander reagiert wird, desto wilder der Regen (und Konfetti). Alle sehen’s live.",
  reactionHeart: "Herz",
  reactionFire: "Lit / stark",
  reactionClap: "Applaus",
  reactionWow: "Überrascht",
  reactionParty: "Feiern",
  reactionSkull: "Ich—",
  reactionSob: "Sobbing (lustig)",
  reactionClown: "Clown-Moment",
  reactionSparkle: "Aura / slay",
  reactionHundred: "100 Prozent",
  reactionGoat: "GOAT",
  reactionSalute: "Respekt",
  reactionCap: "Cap?",
  reactionHandshake: "Fair / deal",
  reactionPopcorn: "Drama geniessen",
  reactionEyes: "Ich schau zu",
  reactionHeartHands: "Herzchen",
  reactionMindBlown: "Mind blown",
} as const;
